In [1]:
import sys
import numpy as np

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1,2,3,4])
b = np.array([0,0.5,1.5,2])

In [4]:
a[0]

1

In [5]:
a[0], a[1]

(1, 2)

In [6]:
a[0:]

array([1, 2, 3, 4])

In [7]:
a[1:-1]

array([2, 3])

In [11]:
### MULTI-INDEXING

b[[0, 2, -1]]

array([0. , 1.5, 2. ])

### Array types

In [12]:
a.dtype

dtype('int64')

In [13]:
np.array([1,2,63], dtype=np.int8)

array([ 1,  2, 63], dtype=int8)

### Dimensions and shapes

In [14]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [15]:
A.shape

(2, 3)

In [16]:
A.ndim

2

In [17]:
A.size

6

In [18]:
B = np.array([
    [123,213,365],
    [31,6,654],
    [123,354,5665]
])

In [19]:
B.shape

(3, 3)

In [21]:
N = np.array([
    [[1,2],[2,3],[3,4],[4,5]],
    [[5,6],[6,7],[7,8],[8,9]],
    [[9,10],[10,11],[11,12],[12,13]]
])

In [22]:
N.shape

(3, 4, 2)

In [23]:
B.ndim

2

In [24]:
N.ndim

3

In [25]:
### get all the last elements from the last dimension
N[:,:,-1]

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [26]:
### get the last element from the first two dimensions
N[-1,-1,:]

array([12, 13])

In [27]:
A[1] = np.array([10,10,10])

In [28]:
A

array([[ 1,  2,  3],
       [10, 10, 10]])

### Summary statistics

In [29]:
a = np.array([1,2,3,4])
a.sum()

10

In [30]:
a.mean()

2.5

In [31]:
a.std()

1.118033988749895

In [32]:
a.var()

1.25

In [33]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])
A.shape

(4, 3)

In [35]:
print(A.sum())
print(A.mean())
print(A.std())
print(A.var())

78
6.5
3.452052529534663
11.916666666666666


In [36]:
A.sum(axis=0)

array([22, 26, 30])

In [37]:
A.sum(axis=1)

array([ 6, 15, 24, 33])

### Broadcasting and Vectorized operations

In [38]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [39]:
a+10

array([10, 11, 12, 13])

In [40]:
a*10

array([ 0, 10, 20, 30])

In [41]:
a += 100

In [42]:
a

array([100, 101, 102, 103])

In [43]:
### to je isto kao i list comprehension
l = [0,1,2,3]
[i * 10 for i in l]

[0, 10, 20, 30]

In [44]:
b = np.array([10,10,10,10])
a + b

array([110, 111, 112, 113])

### Boolean arrays

In [45]:
a[[True,False,False,True]]

array([100, 103])

In [46]:
a[0], a[-1]

(100, 103)

In [52]:
a >= 111

array([False, False, False, False])

In [53]:
a = np.array([1,10,100,1000])

In [54]:
a >= 200

array([False, False, False,  True])

In [55]:
a[a > a.mean()]

array([1000])

In [56]:
a[~(a > a.mean())]

array([  1,  10, 100])

In [57]:
a[(a == 0) & (a % 2 == 0)]

array([], dtype=int64)

In [59]:
A = np.random.randint(100,size=(3,3))
A

array([[46, 68,  0],
       [65, 86, 18],
       [20,  4, 89]])

### Linear Algebra

In [60]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

B = np.array([
    [6,5],
    [4,3],
    [2,1]
])

In [61]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [62]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [63]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [64]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

### Size of objects in memory

In [66]:
sys.getsizeof(1)

28

In [67]:
sys.getsizeof(10**100)

72

In [68]:
np.dtype(np.int8).itemsize

1

In [69]:
np.dtype(np.float64).itemsize

8

In [73]:
l = list(range(1000000))
a = np.arange(1000000)

In [74]:
%time np.sum(a ** 2)

CPU times: user 8.96 ms, sys: 13.3 ms, total: 22.3 ms
Wall time: 44.2 ms


333332833333500000

In [75]:
%time sum([x ** 2 for x in l])

CPU times: user 351 ms, sys: 11.2 ms, total: 362 ms
Wall time: 380 ms


333332833333500000

### Useful python functions

In [76]:
np.random.random(size=2)

array([0.85120947, 0.8625042 ])

In [77]:
np.random.normal(size=2)


array([ 1.05211612, -1.32614247])

In [78]:
np.random.rand(2, 4)


array([[0.76607968, 0.8202845 , 0.8598946 , 0.32038624],
       [0.4019349 , 0.23358614, 0.24228227, 0.72809307]])

In [79]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
np.arange(5, 10)


array([5, 6, 7, 8, 9])

In [81]:
np.arange(0, 1, .1)


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [82]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [83]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [84]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [85]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [86]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [87]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [88]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [90]:
np.zeros((3, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [91]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [92]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [93]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [94]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

In [95]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [96]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [97]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [98]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [99]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

--------------------------------

### Exercises

In [102]:
print(np.__version__)

1.20.1


In [103]:
# Create a numpy array of size 10, filled with zeros.
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [105]:
# Create a numpy array with values ranging from 10 to 49
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [107]:
# Create a numpy matrix of 2*2 integers, filled with ones.
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [108]:
np.ones((2,2),dtype=int)

array([[1, 1],
       [1, 1]])

In [109]:
# Create a numpy matrix of 3*2 float numbers, filled with ones.
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [113]:
np.ones((3,2), dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [114]:
# Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.
X = np.arange(10, dtype=int)
np.ones_like(X)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [115]:
# Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.
np.zeros_like(X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [117]:
# Create a numpy matrix of 4*4 integers, filled with fives.
X = np.array([
    [5,5,5,5],
    [5,5,5,5],
    [5,5,5,5],
    [5,5,5,5]
])
X.shape

(4, 4)

In [118]:
X = np.ones([4,4], dtype=int) * 5
X

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [119]:
# Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.
np.ones_like(X) * 7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [120]:
# Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [121]:
# Create a numpy array, filled with 3 random integer values between 1 and 10.
np.random.randint(10,size=3)

array([1, 9, 2])

In [122]:
# Create a 3*3*3 numpy matrix, filled with random float values.
np.random.rand(3,3,3)

array([[[0.09023354, 0.6368475 , 0.01636099],
        [0.05942234, 0.88201392, 0.44655913],
        [0.14222218, 0.36323354, 0.36731197]],

       [[0.13680049, 0.26343035, 0.29485505],
        [0.72142512, 0.76351835, 0.54401055],
        [0.51226665, 0.81963949, 0.19645822]],

       [[0.69570033, 0.45507495, 0.42642592],
        [0.16931777, 0.08587091, 0.44680033],
        [0.30987728, 0.03476798, 0.54296663]]])

In [123]:
np.random.randn(3,3,3)

array([[[ 0.48154233,  0.22016328,  0.48170965],
        [-1.26263569, -0.08206578, -1.30806692],
        [ 0.27626362, -0.45262799,  0.82015362]],

       [[ 1.51086569,  0.07982584,  0.78580322],
        [-1.98859827, -0.61605948,  2.19893132],
        [-0.0735179 , -1.7681659 ,  0.16888529]],

       [[-0.63711766, -0.08692495,  0.19001528],
        [ 0.11463814,  0.24079439,  0.79719164],
        [ 1.03329664, -2.27755635, -0.32152523]]])

In [125]:
np.random.randint(3,3,3)

ValueError: low >= high

In [127]:
# Given the X python list convert it to an Y numpy array
X = [1,2,3,4]
Y = np.array(X)
Y

array([1, 2, 3, 4])

In [131]:
# Given the X numpy array, make a copy and store it on Y.
X = np.array([[1,2,3],[11,12,13]])
Y = X.copy()
Y

array([[ 1,  2,  3],
       [11, 12, 13]])

In [132]:
# Create a numpy array with numbers from 1 to 10
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [133]:
# Create a numpy array with the odd numbers between 1 to 10
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [135]:
# Create a numpy array with numbers from 1 to 10, in descending order.
np.arange(1,10)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [138]:
# Create a 3*3 numpy matrix, filled with values ranging from 0 to 8
X = np.arange(9).reshape(3,3)
X

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Indexing

In [139]:
# Given the X numpy array, show it's first element
X[0]

array([0, 1, 2])

In [140]:
# Given the X numpy array, show it's last element
X[-1]

array([6, 7, 8])

In [141]:
# Given the X numpy array, show it's first three elements
X[:3]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [142]:
# Given the X numpy array, show all middle elements
X[1:-1]

array([[3, 4, 5]])

In [143]:
# Given the X numpy array, show the elements in reverse position
X[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [144]:
# Given the X numpy matrix, show the first element on first row
X[0,0]

0

In [146]:
# Given the X numpy matrix, show the last element on last row
X[-1,-1]

8

In [148]:
# Given the X numpy matrix, show the middle row elements
X[1:-1]

array([[3, 4, 5]])

In [149]:
# Given the X numpy matrix, show the first two elements on the first two rows
X[:2,:2]

array([[0, 1],
       [3, 4]])

In [150]:
# Given the X numpy matrix, show the last two elements on the last two rows
X[-2:,-2:]

array([[4, 5],
       [7, 8]])

#### Array manipulation

In [154]:
# Order (sort) the given numpy array

X = np.array([0, 10, -5, 40, -3])
X.sort()
X

array([-5, -3,  0, 10, 40])

In [157]:
# Given the X numpy array, set the fifth element equal to 1
X[4] = 1
X

array([-5, -3,  0, 10,  1])

In [163]:
# Given the X numpy matrix, change the last row with all 1
X = np.ones([4,4], dtype=int) * 5
print(X)

X[-1, :] = np.ones(len(X))
X

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [1, 1, 1, 1]])

In [165]:
# Given the X numpy matrix, add 5 to every element
X += 5
X

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [ 6,  6,  6,  6]])

#### Boolean Arrays

In [166]:
# Given the X numpy array, make a mask showing negative elements
mask = X <= 0
mask

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [169]:
# Given the X numpy array, get the negative elements
X = np.array([0, 10, -5, 40, -3])
mask = X < 0
X[mask]

array([-5, -3])

In [170]:
# Given the X numpy array, get numbers higher than 5
fives = X > 5
X[fives]

array([10, 40])

In [171]:
# Given the X numpy array, get numbers higher than the elements mean
mask = X > X.mean()
X[mask]

array([10, 40])

In [173]:
# Given the X numpy array, get numbers equal to 2 or 10
mask = (X == 2) | (X==10)
X[mask]

array([10])

#### Logic functions


In [174]:
# Given the X numpy array, return True if none of its elements is zero
X.all()

False

In [175]:
# Given the X numpy array, return True if any of its elements is zero
X.any()

True

#### Summary statistics

In [176]:
# Given the X numpy array, show the sum of its elements
X.sum()

42

In [177]:
# Given the X numpy matrix, show the sum of its columns
X.sum(axis=0)

42

In [178]:
# Given the X numpy matrix, show the mean value of its rows
X.mean(axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [179]:
# Given the X numpy array, show the max value of its elements
X.max()

40